import { Router } from 'express';
import news_routes from './modules/news/news.routes.js';
import  news_gallery_routes from './modules/news-gallery/news-gallery.routes.js';
import communes_routes from './modules/commune/commune.routes.js';
import provinces_routes from './modules/province/province.routes.js';
import regions_routes from './modules/region/region.routes.js';
import user_role_routes from './modules/user-role/user-role.routes.js';
import user_status_routes from './modules/user-status/user-status.routes.js';
import user_routes from './modules/users/user.routes.js';
import auth_routes from './modules/auth/auth.routes.js';
import editorial_routes from './modules/editorials/editorial.routes.js';
import authors_routes from './modules/authors/author.routes.js';
import subjects_routes from './modules/subjects/subject.routes.js';
import stat_routes from './modules/stats/stat.routes.js';
import copy_routes from './modules/copies/copy.routes.js';
import status_copy_routes from './modules/copy_status/copy_status.routes.js';
import genre_routes from './modules/genres/genre.routes.js';
import edition_routes from './modules/editions/edition.routes.js';
import book_routes from './modules/books/book.routes.js';
import book_author_routes from './modules/book_authors/book_author.routes.js';
import book_subject_routes from './modules/book_subjects/book_subject.routes.js';
import edition_image_routes from './modules/edition-image/edition_image.routes.js';
import reservation_status_routes from './modules/reservation_status/reservation_status.routes.js';
import notification_routes from './modules/notification/notification.routes.js';
import reservation_routes from './modules/reservation/reservation.routes.js';
import loanPolicy_routes from './modules/loan_policy/loan.policy.routes.js';
import loanStatus_routes from './modules/loans-status/loan_status.routes.js';
import loans_routes from './modules/loans/loan.routes.js';
import format_routes from './modules/format/format.routes.js';

const router = Router();

router.use('/api/news', news_routes);
router.use('/api/news-gallery', news_gallery_routes);
router.use('/api/division-commune', communes_routes);
router.use('/api/division-province', provinces_routes);
router.use('/api/division-region', regions_routes);
router.use('/api/user-role', user_role_routes);
router.use('/api/user-status', user_status_routes);
router.use('/api/users', user_routes);
router.use('/api/auth', auth_routes);
router.use('/api/editorial', editorial_routes);
router.use('/api/author', authors_routes);
router.use('/api/subject', subjects_routes);
router.use('/api/stat', stat_routes);
router.use('/api/copy', copy_routes);
router.use('/api/copy-status', status_copy_routes);
router.use('/api/genre', genre_routes);
router.use('/api/edition', edition_routes);
router.use('/api/books', book_routes);
router.use('/api/book-author', book_author_routes);
router.use('/api/book-subject', book_subject_routes);
router.use('/api/edition-image', edition_image_routes);
router.use('/api/reservation-status', reservation_status_routes);
router.use('/api/notifications', notification_routes);
router.use('/api/reservations', reservation_routes);
router.use('/api/loan-policies', loanPolicy_routes);
router.use('/api/loan-status', loanStatus_routes);
router.use('/api/loans', loans_routes);
router.use('/api/format/', format_routes);


export default router;
